version: 2



sources:

  - name: prod_shared
    database: dbt_demo_project_prod
    schema: raw
    tables:
      - name: orders_raw
        description: "order desc"
      - name: country_raw
        description: "country desc"
      - name: customer_raw
        description: ""

  - name: dbt_demo_project
    database: dbt_demo_project
    schema: raw
    tables:
      - name: customer_raw
#        description: ""
      - name: orders_raw
        description: ""
      - name: region_raw
        description: ""
      - name: nation_raw
        description: ""
      - name: country_raw
        description: ""
        columns: 
          - name: nation_key
#            tests: 
#              - unique
        loaded_at_field: load_date
        freshness: 
          error_after: 
            count: 1
            period: day
